name: deploy-test
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Add origin
        run: git remote add secondaryOrigin git@github.com:KarelPetruzela/test-dst.git;

      - name: deploy to other repo
        run: echo "${{ secrets.PK }}" > ~/.ssh/key; `GIT_SSH_COMMAND='ssh -i ~/.ssh/key -o IdentitiesOnly=yes' git push secondaryOrigin master -f
