name: PHP test
on:

  pull_request:
    branches: ["main"]
    paths:
      - "**.yaml"
      - "**.yml"
      - "**.sh"

  workflow_dispatch:

env:
  php-versin: 8.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install php
        run: |
          
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get update
          sudo apt-get install -y \
                "php${{ env.php-version }}" "php${{ env.php-version }}-cli" "php${{ env.php-version }}-intl" "php${{ env.php-version }}-common" "php${{ env.php-version }}-curl" "php${{ env.php-version }}-gd" "php${{ env.php-version }}-fpm" "php${{ env.php-version }}-cgi" \
                "php${{ env.php-version }}-xml" "php${{ env.php-version }}-mbstring" "php${{ env.php-version }}-mysql" "php${{ env.php-version }}-readline" "php${{ env.php-version }}-memcache" \
                "php${{ env.php-version }}-memcached" "php${{ env.php-version }}-ssh2" "php${{ env.php-version }}-tidy" "php${{ env.php-version }}-zip" "php${{ env.php-version }}-dev" "php${{ env.php-version }}-opcache"
          php --version
  
      - name: Install composer
        run: |
          wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet
          sudo mv composer.phar /usr/bin/composer
          sudo chmod +x /usr/bin/composer
          composer_bin=$(composer global config bin-dir --absolute --quiet)
          echo "composer_bin=${composer_bin}" >> "$GITHUB_ENV"
          echo "${composer_bin}" >> "$GITHUB_PATH"
